### ISSUE TITLE
Progressive Web App (PWA) with hop?

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/hop#50]
Are there any examples of Progressive Web Apps for a hop-driven website?

**Comment by manuel-serrano** [comment]
Hi Sven,

I'm not sure what you have precisely in mind, probably because I'm not
sure about the characteristics of a "Progressive Web Apps". What I can
report about is the application I'm using for myself that runs on an
Android phone. The application uses a little Java shell that merely
spawns an Hop server in the background and spawns a fullscreen web
view on that server. It could be that the Java part consisting in
spawning the web view could be replaced with a Progressive manifest
but that I cannot tell.

**Comment by svenha** [comment]
A progressive web app (https://en.wikipedia.org/wiki/Progressive_Web_Apps and https://www.pwabuilder.com/) relies on a web server on the web (and not on the user device). The most (only?) difficult part for using a Hop server seems to be the so-called Service Workers that must be implemented for cases when the device is offline. I was hoping to find a simple example on the web because I am a Scheme expert, but not a Javascript expert :-)
