### ISSUE TITLE
JSON.stringify of a buffer (node.js compat)

### ISSUE THREAD

**Issue by vprunet** [manuel-serrano/hop#53]
Hi Manuel,
We have encountered compatibility issues with node.js related to IPC messages between a master and child process. hop.js triggers an error on the receiving side when the payload contains an UTF8 string. The fix would probably require to update to a recent node.js version of child_process and related files. 
In the mean time, we transcode utf strings to buffers before we send them to hop.js.
Our patch works well when node.js sends data to hop.js, but not in the hop.js to hop.js case.

Here comes the issue (which I'm sure you can fix easily):
JSON.stringify of a buffer builds a string representation of an array, whereas the same operation on node.js builds a string representation of an object. Could you update JSON.stringify so that we get the same behavior as node.js?

Thanks,

Vincent
```
hop --repljs

> var foo =new Buffer( [1, 2, 3]);
undefined
> foo;
<Buffer 01 02 03>
> JSON.stringify( foo );
[1,2,3]
> JSON.parse( JSON.stringify( foo ));
[ 1, 2, 3 ]
```

With node.js
```
> var foo =new Buffer( [1, 2, 3]);
undefined
> foo;
<Buffer 01 02 03>
> JSON.stringify( foo );
'{"type":"Buffer","data":[1,2,3]}'
> JSON.parse( JSON.stringify( foo ));
{ type: 'Buffer', data: [ 1, 2, 3 ] }
```

**Comment by manuel-serrano** [comment]
Hi Vincent,

This problem is actually more annoying that I first thought. The
implementation of STRINGIFY is directly coming from the Node.js
implementation (*). That's very easy to change it for it to behave as
you are suggesting, that is for it to behave as newer Node.js versions
but do we really want to do that? The problem I see with this option is
that if we do that we will create an hybrid version of Node.js incompatible
with all existing official Node.js versions. I'm wondering if it
wouldn't be better to keep it as it is for now.

My priority is to complete the ECMAScript 2017 compatibility. I'm not very
far away from that objective. I think I will be able to reach it by the
beginning of 2019. Then, I could spend some time trying to integrate
the new Node.js JavaScript library and fixing these compatibility issues
with newer Node.js version.

In the meantime, in the preamble of you own applications you can still change
the value of Buffer.prototype.toJSON. Would that be okay for you?

-- 
Manuel

*: In nodejs/buffer.js, you will find:

Buffer.prototype.toJSON = function() {
  return Array.prototype.slice.call(this, 0);
};

**Comment by vprunet** [comment]
Thanks for the hint to Buffer.prototype.toJSON. We'll patch hop.js only in our application.

Vincent
