### ISSUE TITLE
hop option -g can break rendering

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/hop#66]
hop (3.1) option -g can break HTML page rendering. Is this a known problem for -g? If so, it might be helpful to document this prominently. (If this problem is not known, I can add a link to a minimal example.)

**Comment by svenha** [comment]
I saved the pages generated by hop with and without -g. Chromium and derived browsers (Vivaldi, Brave etc.) show the following error, while Firefox does not: 

    Client Error
    Error
    ResizeObserver loop limit exceeded
    object

With -g: http://semantikfabrik.de:8080/static/hop_demo.html

Without -g: http://semantikfabrik.de:8080/static/hop_demo_nodebug.html

**Comment by manuel-serrano** [comment]
I'm able to reproduce that one.

Apparently, the error message "ResizeObserver loop limit exceeded" is
more a warning than a true error (see
https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded).

The problem is that "-g" tries to "help" the programmer by making
error more visible. This is why the panel for reporting the error
shows up, with -g the error goes unoticed on the console. I think it
makes sense to keep it as it is.

**Comment by svenha** [comment]
Agreed. But there should be a warning in the documentation that for this reason (and maybe others) it is not recommended to use -g for production systems.

**Comment by manuel-serrano** [comment]
I did that (for the latest Hop version) and I have added an sentence in the error panel that tells that it is there only because -g is used.

**Comment by svenha** [comment]
Thanks! The error panel sentence is an excellent idea.
