### ISSUE TITLE
Stack overflows

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/hop#85]
My hop servers (64bit, version 3.4.0 to 3.5.0)  report from time to time:

    Stack overflow -- #f

Maybe related because near this message:

    GC Warning: Repeated allocation of very large block (appr. size 2139267072):
    May lead to memory leak and poor performance

How can I track this problem?

**Comment by manuel-serrano** [comment]
Ah very annoying. I guess that you have just no idea where the problem is coming from...
I would first suspect a hashtable. It might be that a hashtable is expanding too much
because when the number of elements goes above a certain threshold the hashtable bucket size doubles.

One general advice would be to configure and compile another Hop version with the --debug configure option. By using that
second version, you will be certain that all type errors are correctly intercepted. The second benefit is that you
can run Hop inside gdb (use something such as gdb --args hop your-usual-argument) because if the stack overflows,
gdb will tell you where this problem occurs. 

Please let me know if this helps.

--
Manuel

ps: BTW, In which language is your application implemented? In Scheme (Hop) or JavaScript?

**Comment by svenha** [comment]
Thanks for the suggestions. I will try a debug version to find the source of the problem. My application is in Scheme.

**Comment by svenha** [comment]
I used a fresh installation of bigloo and hop 3.5.0 afterwards and the stack overflows are gone.
